#!/usr/bin/env bash
#Install nginx web server
sudo apt-get update
sudo apt-get -y install nginx
echo "Holberton School" > /var/www/html/index.nginx-debian.html
sed -i "/server_name _;/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;" /etc/nginx/sites-enabled/default
sudo service nginx restart
