#!/usr/bin/env bash
#Install nginx web server
apt -y update
apt -y install nginx
echo "Holberton School" > /var/www/html/index.nginx-debian.html
sudo sed -i '/server_name _;/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-enabled/default
sudo service nginx restart
