#!/usr/bin/env bash
#Install and configure HAproxy on your lb-01 server.
sudo apt -y update
sudo apt-get -y install haproxy
echo "frontend load_balancer
	bind *:80
	mode http
	default_backend blsoko
backend blsoko
	balance roundrobin
	server 1479-web-01 35.237.88.138:80 check
	server 1479-web-02 34.73.236.77:80 check
" >> /etc/haproxy/haproxy.cfg
sudo service haproxy restart
