#!/usr/bin/env bash
#change localhost ip and facebook.com ip
cp /etc/hosts ~/hosts.new
sudo sed -i s/"127.0.0.1\tlocalhost"/"127.0.0.2\tlocalhost"/ ~/hosts.new
echo "8.8.8.8	facebook.com" >> ~/hosts.new
cp -f ~/hosts.new /etc/hosts
