#!/usr/bin/env bash
# fixing container
sed -i 's/80/8080/g' /etc/nginx/sites-enabled/default
sed -i 's/#user www-data;/#user nginx;/g' /etc/nginx/nginx.conf
chmod 774 /etc/nginx/nginx.conf
sudo service nginx start
sudo su nginx