#!/usr/bin/env bash
# fixing container
sed -i 's/80/8080/g' /etc/nginx/sites-enabled/default
chown -R nginx:nginx /etc/nginx/nginx.conf
chmod 774 /etc/nginx/nginx.conf
sudo -u nginx service nginx restart
